version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_api
    ports:
      - "8000:8000" # Redirige le port 8000 du conteneur vers le port 8000 de l'hôte
    volumes:
      - .:/var/www/html # Monte le répertoire local dans /var/www/html du conteneur
    networks:
      - symfony  # Utilise le réseau défini pour les communications inter-conteneurs
    depends_on:
      - db  # Indique que le conteneur `app` dépend du conteneur `db`
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:latest
    container_name: symfony_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Définit l'utilisateur PostgreSQL (config dans le .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Définit le mot de passe PostgreSQL (config dans le .env)
      POSTGRES_DB: ${POSTGRES_DB}  # Définit la base de données PostgreSQL (config dans le .env)
    ports:
      - "6442:5432"  # Redirige le port 5432 du conteneur vers le port 6442 de l'hôte (5432 ne marche pas sur mon poste)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony  # Utilise le réseau défini pour les communications inter-conteneurs

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  postgres_data:

networks:
  symfony:
    driver: bridge